;; -*- mode: eask; lexical-binding: t -*-

(package "diff-hl"
         "1.10.0"
         "Highlight uncommitted changes using VC")

(website-url "https://github.com/leuven65/diff-hl")
(keywords "vc" "diff")

(package-file "diff-hl.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")  ; Add package archives

(depends-on "emacs" "26.1")
(depends-on "cl-lib")
(depends-on "aio")
